// Side control panel + live training charts. Pure DOM, no framework.

import { TrainStats } from '../sim/vectrain';
import { TaskMode } from '../sim/env';
import { ViewMode } from './level';

export interface UiCallbacks {
  onTrainToggle: () => void;
  onSaveCheckpoint: () => void;
  onLoadCheckpointFile: (file: File) => void;
  onLoadPretrained: () => void;
  onLoadAutosave: () => void;
  onWorldChange: (id: string) => void;
  onWorldReady: (levelId: string, title: string) => void;  // BYOK world finished
  onNewGoal: () => void;
  onTaskChange: (mode: TaskMode, numBalls: number) => void;
  onClimbChange: (height: number) => void;
  onViewMode: (mode: ViewMode) => void;
  onToggleNav: () => void;
  onToggleCameraCollision: () => void;
  onToggleFollow: () => void;
  onToggleGreedy: () => void;
  onRespawn: () => void;
  onSpawnBall: (colorIndex: number) => void;
}

const BALL_COLORS = ['#ef5350', '#42a5f5', '#66bb6a', '#ffee58', '#ab47bc'];

export class Ui {
  private el: HTMLElement;
  private trainBtn!: HTMLButtonElement;
  private stats: Record<string, HTMLElement> = {};
  private chart!: HTMLCanvasElement;
  private returnHistory: number[] = [];
  private successHistory: number[] = [];
  private viewButtons: Record<string, HTMLButtonElement> = {};
  private toggles: Record<string, HTMLButtonElement> = {};
  private worldSelect!: HTMLSelectElement;
  private ballSelect!: HTMLSelectElement;
  private taskButtons: Record<string, HTMLButtonElement> = {};
  taskMode: TaskMode = 'nav';
  training = false;

  private emitTask(mode: TaskMode): void {
    this.taskMode = mode;
    this.taskButtons.nav.classList.toggle('active', mode === 'nav');
    this.taskButtons.fetch.classList.toggle('active', mode === 'fetch');
    this.cb.onTaskChange(mode, parseInt(this.ballSelect.value, 10));
  }

  get numBalls(): number {
    return parseInt(this.ballSelect.value, 10);
  }

  constructor(private cb: UiCallbacks) {
    this.el = document.getElementById('panel')!;
    this.build();
  }

  private build(): void {
    this.el.innerHTML = '';
    this.el.appendChild(h(`
      <div>
        <h1><span class="dot"></span>SpAItial Bot</h1>
        <div class="subtitle">A bot learns to navigate worlds generated by the <b>Spaitial API</b> — PPO ported from <b>PufferLib</b>, training 100% in your browser.</div>
      </div>`));

    // --- World ---
    const world = group('World');
    const row = div('row');
    this.worldSelect = document.createElement('select');
    this.worldSelect.innerHTML = `
      <option value="warehouse">Obstacle Warehouse (training)</option>
      <option value="gallery">Gallery (unseen world)</option>`;
    this.worldSelect.onchange = () => this.cb.onWorldChange(this.worldSelect.value);
    row.appendChild(this.worldSelect);
    world.appendChild(row);
    const customRow = div('row');
    const createBtn = btn('✨ Create your own world', () => this.openCreateDialog());
    createBtn.classList.add('primary');
    customRow.appendChild(createBtn);
    world.appendChild(customRow);
    world.appendChild(h(`<div class="hint">Generate a new world from text or an image with your <b>Spaitial API key</b>. Swap worlds anytime — the policy only sees egocentric lidar, so what it learned transfers.</div>`));
    this.el.appendChild(world);
    this.restoreCreatedWorlds();

    // --- Task ---
    const taskGroup = group('Task');
    const trow1 = div('row');
    this.taskButtons.nav = btn('🧭 Navigate', () => this.emitTask('nav'));
    this.taskButtons.fetch = btn('🔵 Fetch balls', () => this.emitTask('fetch'));
    this.taskButtons.nav.classList.add('active');
    trow1.appendChild(this.taskButtons.nav);
    trow1.appendChild(this.taskButtons.fetch);
    taskGroup.appendChild(trow1);
    const trow2 = div('row');
    this.ballSelect = document.createElement('select');
    for (let n = 1; n <= 8; n++) {
      const o = document.createElement('option');
      o.value = String(n);
      o.textContent = `${n} ball${n > 1 ? 's' : ''} to collect`;
      this.ballSelect.appendChild(o);
    }
    this.ballSelect.value = '4';
    this.ballSelect.onchange = () => this.emitTask(this.taskMode);
    trow2.appendChild(this.ballSelect);
    taskGroup.appendChild(trow2);
    taskGroup.appendChild(h(`<div class="hint">Fetch: collect every <b>blue</b> ball (one at a time) and drop it at the green goal — other colors are decoys. Training starts at 1 ball and ramps up.</div>`));
    this.el.appendChild(taskGroup);

    // --- Training ---
    const training = group('Training');
    const trow = div('row');
    this.trainBtn = btn('▶ Start learning', () => this.cb.onTrainToggle());
    this.trainBtn.classList.add('primary');
    trow.appendChild(this.trainBtn);
    training.appendChild(trow);

    const grid = div('stat-grid');
    for (const [key, label] of [
      ['steps', 'Env steps'], ['sps', 'Steps/sec'],
      ['success', 'Success rate'], ['return', 'Mean return'],
      ['eplen', 'Episode len'], ['curriculum', 'Goal dist (max)'],
    ] as const) {
      grid.appendChild(h(`<div class="k">${label === 'Goal dist (max)' ? 'Curriculum' : label}</div>`));
      const v = h(`<div class="v">—</div>`);
      this.stats[key] = v;
      grid.appendChild(v);
    }
    training.appendChild(grid);

    this.chart = document.createElement('canvas');
    this.chart.id = 'chart';
    this.chart.width = 272 * devicePixelRatio;
    this.chart.height = 90 * devicePixelRatio;
    training.appendChild(this.chart);
    training.appendChild(h(`<div class="hint"><span style="color:#4fc3f7">━</span> mean return&nbsp;&nbsp;<span style="color:#69f0ae">━</span> success rate</div>`));
    this.el.appendChild(training);

    // --- Checkpoints ---
    const ckpt = group('Checkpoints');
    const crow1 = div('row');
    crow1.appendChild(btn('💾 Save', () => this.cb.onSaveCheckpoint()));
    const fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = '.pfbt';
    fileInput.className = 'file-input';
    fileInput.onchange = () => { if (fileInput.files?.[0]) this.cb.onLoadCheckpointFile(fileInput.files[0]); fileInput.value = ''; };
    crow1.appendChild(fileInput);
    crow1.appendChild(btn('📂 Load file', () => fileInput.click()));
    ckpt.appendChild(crow1);
    const crow2 = div('row');
    crow2.appendChild(btn('⚡ Load pretrained', () => this.cb.onLoadPretrained()));
    crow2.appendChild(btn('🕘 Autosave', () => this.cb.onLoadAutosave()));
    ckpt.appendChild(crow2);
    this.el.appendChild(ckpt);

    // --- Bot ---
    const bot = group('Bot');
    const brow = div('row');
    this.toggles.follow = btn('🎥 Follow', () => this.cb.onToggleFollow());
    this.toggles.follow.classList.add('active');
    this.toggles.greedy = btn('🎯 Greedy', () => this.cb.onToggleGreedy());
    brow.appendChild(this.toggles.follow);
    brow.appendChild(this.toggles.greedy);
    brow.appendChild(btn('♻ Respawn <kbd>R</kbd>', () => this.cb.onRespawn()));
    brow.appendChild(btn('🎲 New goal', () => this.cb.onNewGoal()));
    bot.appendChild(brow);
    const crow = div('row');
    const climbSelect = document.createElement('select');
    climbSelect.innerHTML = `
      <option value="0">Climbing off (stairs only)</option>
      <option value="0.35">Climb ≤ 0.35 m</option>
      <option value="0.5" selected>Climb ≤ 0.5 m</option>
      <option value="0.7">Climb ≤ 0.7 m</option>`;
    climbSelect.onchange = () => this.cb.onClimbChange(parseFloat(climbSelect.value));
    crow.appendChild(climbSelect);
    bot.appendChild(crow);
    bot.appendChild(h(`<div class="hint"><b>Click anywhere on the floor</b> to set the goal yourself — the bot walks there. Drag to orbit, wheel to zoom, <kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><kbd>Q</kbd><kbd>E</kbd> to fly the camera (turns Follow off).</div>`));
    this.el.appendChild(bot);

    // --- View ---
    const view = group('View');
    const vrow = div('row');
    const modes: [string, ViewMode, string][] = [
      ['Splat + Bot', 'both', 'B'], ['Mesh overlay', 'mesh-overlay', 'M'],
      ['Splat only', 'splat-only', 'P'], ['Mesh only', 'mesh-only', 'O'],
    ];
    for (const [label, mode, key] of modes) {
      const b = btn(`${label} <kbd>${key}</kbd>`, () => this.cb.onViewMode(mode));
      this.viewButtons[mode] = b;
      vrow.appendChild(b);
    }
    view.appendChild(vrow);
    const vrow2 = div('row');
    this.toggles.nav = btn('Navgrid <kbd>N</kbd>', () => this.cb.onToggleNav());
    this.toggles.cam = btn('Cam collision <kbd>C</kbd>', () => this.cb.onToggleCameraCollision());
    vrow2.appendChild(this.toggles.nav);
    vrow2.appendChild(this.toggles.cam);
    view.appendChild(vrow2);
    this.setViewMode('both');
    this.el.appendChild(view);

    // --- Physics toys ---
    const balls = group('Physics balls');
    const prow = div('row');
    BALL_COLORS.forEach((c, i) => {
      const b = btn(`<span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:${c}"></span> <kbd>${i + 1}</kbd>`, () => this.cb.onSpawnBall(i));
      prow.appendChild(b);
    });
    balls.appendChild(prow);
    this.el.appendChild(balls);
  }

  setTraining(on: boolean): void {
    this.training = on;
    this.trainBtn.innerHTML = on ? '⏸ Pause learning' : '▶ Start learning';
    this.trainBtn.classList.toggle('active', on);
  }

  setToggle(name: 'follow' | 'greedy' | 'nav' | 'cam', on: boolean): void {
    this.toggles[name]?.classList.toggle('active', on);
  }

  setViewMode(mode: ViewMode): void {
    for (const [m, b] of Object.entries(this.viewButtons)) b.classList.toggle('active', m === mode);
  }

  setWorld(id: string): void {
    this.worldSelect.value = id;
  }

  // register a custom world in the dropdown (or just select it if present)
  addCustomWorld(id: string, label: string): void {
    if (![...this.worldSelect.options].some((o) => o.value === id)) {
      const opt = document.createElement('option');
      opt.value = id;
      opt.textContent = label;
      this.worldSelect.appendChild(opt);
    }
    this.worldSelect.value = id;
  }

  updateStats(s: TrainStats, totalSteps: number): void {
    this.stats.steps.textContent = formatNum(totalSteps);
    this.stats.sps.textContent = formatNum(s.sps);
    this.stats.success.textContent = `${(s.successRate * 100).toFixed(0)} %`;
    this.stats.return.textContent = s.meanReturn.toFixed(2);
    this.stats.eplen.textContent = s.meanEpLen.toFixed(0);
    this.stats.curriculum.textContent = this.taskMode === 'fetch'
      ? `${s.curriculum.toFixed(0)} ball${s.curriculum > 1 ? 's' : ''}`
      : `${s.curriculum.toFixed(1)} m`;
    this.returnHistory.push(s.meanReturn);
    this.successHistory.push(s.successRate);
    if (this.returnHistory.length > 400) { this.returnHistory.shift(); this.successHistory.shift(); }
    this.drawChart();
  }

  private drawChart(): void {
    const ctx = this.chart.getContext('2d')!;
    const W = this.chart.width, H = this.chart.height;
    ctx.clearRect(0, 0, W, H);
    const series = (data: number[], color: string, lo: number, hi: number) => {
      if (data.length < 2) return;
      ctx.strokeStyle = color;
      ctx.lineWidth = 1.5 * devicePixelRatio;
      ctx.beginPath();
      for (let i = 0; i < data.length; i++) {
        const x = (i / (data.length - 1)) * W;
        const yNorm = (data[i] - lo) / Math.max(hi - lo, 1e-6);
        const y = H - 4 - yNorm * (H - 8);
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      }
      ctx.stroke();
    };
    const rMin = Math.min(...this.returnHistory, 0), rMax = Math.max(...this.returnHistory, 1);
    series(this.returnHistory, '#4fc3f7', rMin, rMax);
    series(this.successHistory, '#69f0ae', 0, 1);
  }

  // ---------------- BYOK world creation dialog ----------------

  private restoreCreatedWorlds(): void {
    try {
      const list = JSON.parse(localStorage.getItem('spaitial-created-worlds') ?? '[]') as { id: string; title: string }[];
      for (const w of list) {
        const opt = document.createElement('option');
        opt.value = `created:${w.id}`;
        opt.textContent = `✨ ${w.title}`;
        this.worldSelect.appendChild(opt);
      }
    } catch { /* corrupt list — ignore */ }
  }

  rememberCreatedWorld(id: string, title: string): void {
    try {
      const list = JSON.parse(localStorage.getItem('spaitial-created-worlds') ?? '[]') as { id: string; title: string }[];
      if (!list.some((w) => w.id === id)) {
        list.push({ id, title });
        localStorage.setItem('spaitial-created-worlds', JSON.stringify(list));
      }
    } catch { /* ok */ }
  }

  private openCreateDialog(): void {
    const overlay = document.getElementById('dialog-overlay')!;
    overlay.innerHTML = '';
    const card = h(`
      <div class="dialog">
        <h2>✨ Create a world with the Spaitial API</h2>
        <div class="sub">Bring your own key from <a href="https://developers.spaitial.ai" target="_blank" style="color:var(--accent)">developers.spaitial.ai</a>.
        Generation takes ~5–10 minutes and produces a gaussian splat <b>plus a collision mesh</b>, so the bot gets full physics, climbing, and training support.</div>
        <label>Spaitial API key</label>
        <input type="password" id="byok-key" placeholder="spt_live_…" autocomplete="off" />
        <label>Describe the world (text → world)</label>
        <textarea id="byok-prompt" placeholder="an empty indoor obstacle course with low wooden platforms, crates and ramps on a concrete floor"></textarea>
        <label>…or generate from an image</label>
        <input type="file" id="byok-image" accept="image/jpeg,image/png,image/webp" />
        <div class="row" style="margin-top:14px">
          <button class="primary" id="byok-go">🚀 Generate world</button>
          <button id="byok-close">Close</button>
        </div>
        <div class="progress" id="byok-progress"></div>
        <div class="hint" style="margin-top:10px">Your key goes only to your local dev server, is held in memory for this job, and is never stored on disk. It is remembered in this browser (localStorage) for convenience.</div>
      </div>`);
    overlay.appendChild(card);
    overlay.classList.add('open');

    const keyInput = card.querySelector('#byok-key') as HTMLInputElement;
    const promptInput = card.querySelector('#byok-prompt') as HTMLTextAreaElement;
    const imageInput = card.querySelector('#byok-image') as HTMLInputElement;
    const goBtn = card.querySelector('#byok-go') as HTMLButtonElement;
    const progress = card.querySelector('#byok-progress') as HTMLElement;
    keyInput.value = localStorage.getItem('spaitial-api-key') ?? '';

    let polling: ReturnType<typeof setInterval> | null = null;
    const close = () => {
      if (polling) clearInterval(polling);
      overlay.classList.remove('open');
    };
    (card.querySelector('#byok-close') as HTMLButtonElement).onclick = close;
    overlay.onclick = (e) => { if (e.target === overlay) close(); };

    const showProgress = (msg: string, spin = true) => {
      progress.classList.add('show');
      progress.innerHTML = `${spin ? '<span class="spinner"></span>' : ''}${msg}`;
    };

    goBtn.onclick = async () => {
      const key = keyInput.value.trim();
      if (!key.startsWith('spt_')) { showProgress('Enter a valid API key (spt_live_… / spt_test_…)', false); return; }
      localStorage.setItem('spaitial-api-key', key);

      const body: { prompt?: string; imageBase64?: string } = {};
      if (imageInput.files?.[0]) {
        showProgress('Reading image…');
        body.imageBase64 = await fileToDataUri(imageInput.files[0]);
      } else if (promptInput.value.trim()) {
        body.prompt = promptInput.value.trim();
      } else {
        showProgress('Describe the world or pick an image first', false);
        return;
      }

      goBtn.disabled = true;
      showProgress('Submitting to api.spaitial.ai…');
      try {
        const res = await fetch('/ext/create-world', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-spaitial-key': key },
          body: JSON.stringify(body),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data?.error?.message ?? data?.error ?? `HTTP ${res.status}`);
        const reqId = data.request_id as string;
        const started = Date.now();
        const PHASE_LABEL: Record<string, string> = {
          generating: 'Generating world (5–10 min)',
          downloading: 'Downloading splat',
          'mesh-export': 'Exporting collision mesh',
          converting: 'Converting for PlayCanvas',
        };
        polling = setInterval(async () => {
          try {
            const st = await (await fetch(`/ext/created/${reqId}/status`)).json();
            const mins = ((Date.now() - started) / 60000).toFixed(1);
            if (st.phase === 'ready') {
              if (polling) clearInterval(polling);
              const title = st.title || `World ${reqId.slice(4, 10)}`;
              this.rememberCreatedWorld(reqId, title);
              this.addCustomWorld(`created:${reqId}`, `✨ ${title}`);
              showProgress(`✅ <b>${title}</b> is ready — loading…`, false);
              setTimeout(() => { close(); this.cb.onWorldReady(`created:${reqId}`, title); }, 800);
            } else if (st.phase === 'error') {
              if (polling) clearInterval(polling);
              goBtn.disabled = false;
              showProgress(`❌ ${st.error ?? 'generation failed'}`, false);
            } else {
              showProgress(`${PHASE_LABEL[st.phase] ?? st.phase}${st.detail ? ` — ${st.detail}` : ''} · ${mins} min elapsed`);
            }
          } catch { /* transient poll error */ }
        }, 5000);
        showProgress(`${PHASE_LABEL.generating} — submitted`);
      } catch (e) {
        goBtn.disabled = false;
        showProgress(`❌ ${(e as Error).message}`, false);
      }
    };
  }

  toast(message: string): void {
    const t = document.getElementById('toast')!;
    t.textContent = message;
    t.classList.add('show');
    clearTimeout((t as any)._timer);
    (t as any)._timer = setTimeout(() => t.classList.remove('show'), 2600);
  }
}

function fileToDataUri(file: File): Promise<string> {
  return new Promise((res, rej) => {
    const r = new FileReader();
    r.onload = () => res(r.result as string);
    r.onerror = () => rej(new Error('could not read image'));
    r.readAsDataURL(file);
  });
}

function h(html: string): HTMLElement {
  const tpl = document.createElement('template');
  tpl.innerHTML = html.trim();
  return tpl.content.firstElementChild as HTMLElement;
}
function div(cls: string): HTMLElement {
  const d = document.createElement('div');
  d.className = cls;
  return d;
}
function btn(html: string, onClick: () => void): HTMLButtonElement {
  const b = document.createElement('button');
  b.innerHTML = html;
  b.onclick = onClick;
  return b;
}
function group(label: string): HTMLElement {
  const g = div('group');
  g.appendChild(h(`<div class="group-label">${label}</div>`));
  return g;
}
function formatNum(n: number): string {
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'k';
  return String(n);
}
