// Side control panel + live training charts. Pure DOM, no framework.

import { TrainStats } from '../sim/vectrain';
import { TaskMode } from '../sim/env';
import { ViewMode } from './level';

export interface UiCallbacks {
  onTrainToggle: () => void;
  onResetPolicy: () => void;
  onSaveCheckpoint: () => void;
  onLoadCheckpointFile: (file: File) => void;
  onLoadPretrained: () => void;
  onLoadAutosave: () => void;
  onWorldChange: (id: string) => void;
  onWorldReady: (levelId: string, title: string) => void;  // BYOK world finished
  onNewGoal: () => void;
  onTaskChange: (mode: TaskMode, numBalls: number) => void;
  onClimbChange: (height: number) => void;
  onViewMode: (mode: ViewMode) => void;
  onToggleNav: () => void;
  onToggleCameraCollision: () => void;
  onToggleFollow: () => void;
  onRespawn: () => void;
  onSpawnBall: (colorIndex: number) => void;
}

const BALL_COLORS = ['#ef5350', '#42a5f5', '#66bb6a', '#ffee58', '#ab47bc'];

const PENDING_KEY = 'spaitial-pending-gen';
const PHASE_LABEL: Record<string, string> = {
  generating: 'Generating world (5–10 min)',
  downloading: 'Downloading splat',
  'mesh-export': 'Exporting collision mesh',
  converting: 'Converting for PlayCanvas',
};

interface PendingGen { reqId: string; title: string; startedAt: number }
interface GenEntry extends PendingGen { phase: string; detail?: string; error?: string; ready?: boolean }

export class Ui {
  private el: HTMLElement;
  private trainBtn!: HTMLButtonElement;
  private stats: Record<string, HTMLElement> = {};
  private chart!: HTMLCanvasElement;
  private returnHistory: number[] = [];
  private successHistory: number[] = [];
  private viewButtons: Record<string, HTMLButtonElement> = {};
  private toggles: Record<string, HTMLButtonElement> = {};
  private worldSelect!: HTMLSelectElement;
  private ballSelect!: HTMLSelectElement;
  private taskButtons: Record<string, HTMLButtonElement> = {};
  private genChip!: HTMLElement;
  private pretrainedBtn!: HTMLButtonElement;
  private createBtn!: HTMLButtonElement;
  private worldHint!: HTMLElement;
  backendAvailable = true;
  private genState = new Map<string, GenEntry>();
  private genPoll: ReturnType<typeof setInterval> | null = null;
  private dialogReqId: string | null = null;        // job the open dialog is watching
  private dialogProgressEl: HTMLElement | null = null;
  taskMode: TaskMode = 'nav';
  training = false;

  private emitTask(mode: TaskMode): void {
    this.taskMode = mode;
    this.taskButtons.nav.classList.toggle('active', mode === 'nav');
    this.taskButtons.fetch.classList.toggle('active', mode === 'fetch');
    this.cb.onTaskChange(mode, parseInt(this.ballSelect.value, 10));
  }

  get numBalls(): number {
    return parseInt(this.ballSelect.value, 10);
  }

  constructor(private cb: UiCallbacks) {
    this.el = document.getElementById('panel')!;
    this.build();
  }

  private build(): void {
    this.el.innerHTML = '';
    this.el.appendChild(h(`
      <div>
        <h1><span class="dot"></span>SpAItial Bot</h1>
        <div class="subtitle">A bot learns to navigate worlds generated by the <b>Spaitial API</b> — PPO ported from <b>PufferLib</b>, training 100% in your browser.</div>
      </div>`));

    // --- World ---
    const world = group('World');
    const row = div('row');
    this.worldSelect = document.createElement('select');
    this.worldSelect.innerHTML = `
      <option value="gallery">Gallery (training)</option>
      <option value="warehouse">Obstacle Warehouse (unseen test)</option>`;
    this.worldSelect.onchange = () => this.cb.onWorldChange(this.worldSelect.value);
    row.appendChild(this.worldSelect);
    world.appendChild(row);
    const customRow = div('row');
    this.createBtn = btn('✨ Create your own world', () => this.openCreateDialog());
    this.createBtn.classList.add('primary');
    customRow.appendChild(this.createBtn);
    world.appendChild(customRow);
    this.genChip = h(`<div class="gen-chip" style="display:none" title="Click to open the generation dialog"></div>`);
    this.genChip.onclick = () => this.openCreateDialog();
    world.appendChild(this.genChip);
    this.worldHint = h(`<div class="hint">Generate a new world from text or an image with your <b>Spaitial API key</b>. Swap worlds anytime — the policy only sees egocentric lidar, so what it learned transfers.</div>`);
    world.appendChild(this.worldHint);
    this.el.appendChild(world);
    this.restoreCreatedWorlds();
    this.resumePending();

    // --- Task ---
    const taskGroup = group('Task');
    const trow1 = div('row');
    this.taskButtons.nav = btn('🧭 Navigate', () => this.emitTask('nav'));
    this.taskButtons.fetch = btn('🔵 Fetch balls', () => this.emitTask('fetch'));
    this.taskButtons.nav.classList.add('active');
    trow1.appendChild(this.taskButtons.nav);
    trow1.appendChild(this.taskButtons.fetch);
    taskGroup.appendChild(trow1);
    const trow2 = div('row');
    this.ballSelect = document.createElement('select');
    for (let n = 1; n <= 8; n++) {
      const o = document.createElement('option');
      o.value = String(n);
      o.textContent = `${n} ball${n > 1 ? 's' : ''} to collect`;
      this.ballSelect.appendChild(o);
    }
    this.ballSelect.value = '4';
    this.ballSelect.onchange = () => this.emitTask(this.taskMode);
    trow2.appendChild(this.ballSelect);
    taskGroup.appendChild(trow2);
    taskGroup.appendChild(h(`<div class="hint">Fetch: collect every <b>blue</b> ball (one at a time) and drop it at the green goal — other colors are decoys. Training starts at 1 ball and ramps up.</div>`));
    this.el.appendChild(taskGroup);

    // --- Training ---
    const training = group('Training');
    const trow = div('row');
    this.trainBtn = btn('▶ Start learning', () => this.cb.onTrainToggle());
    this.trainBtn.classList.add('primary');
    trow.appendChild(this.trainBtn);
    trow.appendChild(btn('↺ Reset', () => this.cb.onResetPolicy()));
    training.appendChild(trow);
    training.appendChild(h(`<div class="hint">The bot starts on the <b>pretrained</b> policy. <b>Start learning</b> fine-tunes it live; <b>↺ Reset</b> wipes to a random policy so you can watch it learn from scratch.</div>`));

    const grid = div('stat-grid');
    for (const [key, label] of [
      ['steps', 'Env steps'], ['sps', 'Steps/sec'],
      ['success', 'Success rate'], ['return', 'Mean return'],
      ['eplen', 'Episode len'], ['curriculum', 'Goal dist (max)'],
    ] as const) {
      grid.appendChild(h(`<div class="k">${label === 'Goal dist (max)' ? 'Curriculum' : label}</div>`));
      const v = h(`<div class="v">—</div>`);
      this.stats[key] = v;
      grid.appendChild(v);
    }
    training.appendChild(grid);

    this.chart = document.createElement('canvas');
    this.chart.id = 'chart';
    this.chart.width = 272 * devicePixelRatio;
    this.chart.height = 90 * devicePixelRatio;
    training.appendChild(this.chart);
    training.appendChild(h(`<div class="hint"><span style="color:#4fc3f7">━</span> mean return&nbsp;&nbsp;<span style="color:#69f0ae">━</span> success rate</div>`));
    this.el.appendChild(training);

    // --- Checkpoints ---
    const ckpt = group('Checkpoints');
    const crow1 = div('row');
    crow1.appendChild(btn('💾 Save', () => this.cb.onSaveCheckpoint()));
    const fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = '.pfbt';
    fileInput.className = 'file-input';
    fileInput.onchange = () => { if (fileInput.files?.[0]) this.cb.onLoadCheckpointFile(fileInput.files[0]); fileInput.value = ''; };
    crow1.appendChild(fileInput);
    crow1.appendChild(btn('📂 Load file', () => fileInput.click()));
    ckpt.appendChild(crow1);
    const crow2 = div('row');
    this.pretrainedBtn = btn('⚡ Load pretrained', () => this.cb.onLoadPretrained());
    crow2.appendChild(this.pretrainedBtn);
    crow2.appendChild(btn('🕘 Autosave', () => this.cb.onLoadAutosave()));
    ckpt.appendChild(crow2);
    this.el.appendChild(ckpt);

    // --- Bot ---
    const bot = group('Bot');
    const brow = div('row');
    this.toggles.follow = btn('🎥 Follow', () => this.cb.onToggleFollow());
    this.toggles.follow.classList.add('active');
    brow.appendChild(this.toggles.follow);
    brow.appendChild(btn('♻ Respawn <kbd>R</kbd>', () => this.cb.onRespawn()));
    brow.appendChild(btn('🎲 New goal', () => this.cb.onNewGoal()));
    bot.appendChild(brow);
    const crow = div('row');
    const climbSelect = document.createElement('select');
    climbSelect.innerHTML = `
      <option value="0">Climbing off (stairs only)</option>
      <option value="0.35">Climb ≤ 0.35 m</option>
      <option value="0.5" selected>Climb ≤ 0.5 m</option>
      <option value="0.7">Climb ≤ 0.7 m</option>`;
    climbSelect.onchange = () => this.cb.onClimbChange(parseFloat(climbSelect.value));
    crow.appendChild(climbSelect);
    bot.appendChild(crow);
    bot.appendChild(h(`<div class="hint"><b>Click anywhere on the floor</b> to set the goal yourself — the bot walks there. Drag to orbit, wheel to zoom, <kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><kbd>Q</kbd><kbd>E</kbd> to fly the camera (turns Follow off).</div>`));
    this.el.appendChild(bot);

    // --- View ---
    const view = group('View');
    const vrow = div('row');
    const modes: [string, ViewMode, string][] = [
      ['Splat + Bot', 'both', 'B'], ['Mesh overlay', 'mesh-overlay', 'M'],
      ['Splat only', 'splat-only', 'P'], ['Mesh only', 'mesh-only', 'O'],
    ];
    for (const [label, mode, key] of modes) {
      const b = btn(`${label} <kbd>${key}</kbd>`, () => this.cb.onViewMode(mode));
      this.viewButtons[mode] = b;
      vrow.appendChild(b);
    }
    view.appendChild(vrow);
    const vrow2 = div('row');
    this.toggles.nav = btn('Navgrid <kbd>N</kbd>', () => this.cb.onToggleNav());
    this.toggles.cam = btn('Cam collision <kbd>C</kbd>', () => this.cb.onToggleCameraCollision());
    vrow2.appendChild(this.toggles.nav);
    vrow2.appendChild(this.toggles.cam);
    view.appendChild(vrow2);
    this.setViewMode('both');
    this.el.appendChild(view);

    // --- Physics toys ---
    const balls = group('Physics balls');
    const prow = div('row');
    BALL_COLORS.forEach((c, i) => {
      const b = btn(`<span style="display:inline-block;width:12px;height:12px;border-radius:50%;background:${c}"></span> <kbd>${i + 1}</kbd>`, () => this.cb.onSpawnBall(i));
      prow.appendChild(b);
    });
    balls.appendChild(prow);
    this.el.appendChild(balls);
  }

  setTraining(on: boolean): void {
    this.training = on;
    this.trainBtn.innerHTML = on ? '⏸ Pause learning' : '▶ Start learning';
    this.trainBtn.classList.toggle('active', on);
  }

  // reflect whether the bundled pretrained policy is currently active
  setPretrainedActive(on: boolean): void {
    this.pretrainedBtn.classList.toggle('ckpt-active', on);
    this.pretrainedBtn.innerHTML = on ? '✓ Pretrained loaded' : '⚡ Load pretrained';
  }

  setToggle(name: 'follow' | 'nav' | 'cam', on: boolean): void {
    this.toggles[name]?.classList.toggle('active', on);
  }

  setViewMode(mode: ViewMode): void {
    for (const [m, b] of Object.entries(this.viewButtons)) b.classList.toggle('active', m === mode);
  }

  setWorld(id: string): void {
    this.worldSelect.value = id;
  }

  // register a custom world in the dropdown; select=false adds it without
  // changing the user's current world (used when a background job finishes)
  addCustomWorld(id: string, label: string, select = true): void {
    if (![...this.worldSelect.options].some((o) => o.value === id)) {
      const opt = document.createElement('option');
      opt.value = id;
      opt.textContent = label;
      this.worldSelect.appendChild(opt);
    }
    if (select) this.worldSelect.value = id;
  }

  updateStats(s: TrainStats, totalSteps: number): void {
    this.stats.steps.textContent = formatNum(totalSteps);
    this.stats.sps.textContent = formatNum(s.sps);
    this.stats.success.textContent = `${(s.successRate * 100).toFixed(0)} %`;
    this.stats.return.textContent = s.meanReturn.toFixed(2);
    this.stats.eplen.textContent = s.meanEpLen.toFixed(0);
    this.stats.curriculum.textContent = this.taskMode === 'fetch'
      ? `${s.curriculum.toFixed(0)} ball${s.curriculum > 1 ? 's' : ''}`
      : `${s.curriculum.toFixed(1)} m`;
    this.returnHistory.push(s.meanReturn);
    this.successHistory.push(s.successRate);
    if (this.returnHistory.length > 400) { this.returnHistory.shift(); this.successHistory.shift(); }
    this.drawChart();
  }

  private drawChart(): void {
    const ctx = this.chart.getContext('2d')!;
    const W = this.chart.width, H = this.chart.height;
    ctx.clearRect(0, 0, W, H);
    const series = (data: number[], color: string, lo: number, hi: number) => {
      if (data.length < 2) return;
      ctx.strokeStyle = color;
      ctx.lineWidth = 1.5 * devicePixelRatio;
      ctx.beginPath();
      for (let i = 0; i < data.length; i++) {
        const x = (i / (data.length - 1)) * W;
        const yNorm = (data[i] - lo) / Math.max(hi - lo, 1e-6);
        const y = H - 4 - yNorm * (H - 8);
        if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
      }
      ctx.stroke();
    };
    const rMin = Math.min(...this.returnHistory, 0), rMax = Math.max(...this.returnHistory, 1);
    series(this.returnHistory, '#4fc3f7', rMin, rMax);
    series(this.successHistory, '#69f0ae', 0, 1);
  }

  // ---------------- BYOK world creation dialog ----------------

  private restoreCreatedWorlds(): void {
    try {
      const list = JSON.parse(localStorage.getItem('spaitial-created-worlds') ?? '[]') as { id: string; title: string }[];
      for (const w of list) {
        const opt = document.createElement('option');
        opt.value = `created:${w.id}`;
        opt.textContent = `✨ ${w.title}`;
        this.worldSelect.appendChild(opt);
      }
    } catch { /* corrupt list — ignore */ }
  }

  rememberCreatedWorld(id: string, title: string): void {
    try {
      const list = JSON.parse(localStorage.getItem('spaitial-created-worlds') ?? '[]') as { id: string; title: string }[];
      if (!list.some((w) => w.id === id)) {
        list.push({ id, title });
        localStorage.setItem('spaitial-created-worlds', JSON.stringify(list));
      }
    } catch { /* ok */ }
  }

  // called from boot once we know whether the generation backend is reachable
  setBackendAvailable(ok: boolean): void {
    this.backendAvailable = ok;
    if (!ok) {
      this.createBtn.textContent = '✨ Create a world (local setup)';
      this.worldHint.innerHTML = 'This is the hosted demo — try the two bundled worlds and watch the bot learn. <b>Creating new worlds</b> from text/images needs your Spaitial API key, which only works when you run the project locally (<code>npm run dev</code>). See the repo README.';
    }
  }

  private openCreateDialog(): void {
    const overlay = document.getElementById('dialog-overlay')!;
    overlay.innerHTML = '';
    if (!this.backendAvailable) {
      const info = h(`
        <div class="dialog">
          <h2>✨ Create your own world</h2>
          <div class="sub">World generation talks to the Spaitial API and converts the result, which needs the project's local dev server — it isn't available on this hosted demo.</div>
          <div class="hint" style="line-height:1.6">To create worlds from a text prompt or a photo with your own <a href="https://developers.spaitial.ai" target="_blank" style="color:var(--accent)">Spaitial API key</a>:
          <ol style="margin:8px 0 0; padding-left:18px">
            <li>Clone the repo and run <code>npm install</code></li>
            <li><code>npm run dev</code></li>
            <li>Open the printed URL and hit “Create your own world”</li>
          </ol></div>
          <div class="row" style="margin-top:14px"><button id="byok-close">Got it</button></div>
        </div>`);
      overlay.appendChild(info);
      overlay.classList.add('open');
      (info.querySelector('#byok-close') as HTMLButtonElement).onclick = () => overlay.classList.remove('open');
      overlay.onclick = (e) => { if (e.target === overlay) overlay.classList.remove('open'); };
      return;
    }
    const card = h(`
      <div class="dialog">
        <h2>✨ Create a world with the Spaitial API</h2>
        <div class="sub">Bring your own key from <a href="https://developers.spaitial.ai" target="_blank" style="color:var(--accent)">developers.spaitial.ai</a>.
        Generation produces a gaussian splat <b>plus a collision mesh</b> (full physics, climbing, training). Already made one? Reuse it below — no waiting.</div>
        <label>Spaitial API key</label>
        <input type="password" id="byok-key" placeholder="spt_live_…" autocomplete="off" />
        <label>Describe the world (text → world)</label>
        <textarea id="byok-prompt" placeholder="an empty indoor obstacle course with low wooden platforms, crates and ramps on a concrete floor"></textarea>
        <label>…or generate from an image</label>
        <input type="file" id="byok-image" accept="image/jpeg,image/png,image/webp" />
        <div class="row" style="margin-top:14px">
          <button class="primary" id="byok-go">🚀 Generate world</button>
          <button id="byok-close">Close</button>
        </div>
        <div style="border-top:1px solid rgba(255,255,255,0.1); margin:16px 0 0; padding-top:12px"></div>
        <label>Reuse a world already generated with this key</label>
        <div class="row" style="margin-top:0">
          <input type="text" id="byok-import" class="link-input" placeholder="request ID — req_…" />
          <button id="byok-import-go">📥 Import</button>
        </div>
        <div class="hint">Skip generation — pull an existing world's splat + mesh straight from the API by its <b>request ID</b>. Find your <code>req_…</code> IDs at <a href="https://developers.spaitial.ai/generations" target="_blank" style="color:var(--accent)">developers.spaitial.ai/generations</a>.</div>
        <div class="progress" id="byok-progress"></div>
        <div class="hint" style="margin-top:10px">Your key goes only to your local dev server, is held in memory for this job, and is never stored on disk. It is remembered in this browser (localStorage) for convenience.</div>
      </div>`);
    overlay.appendChild(card);
    overlay.classList.add('open');

    const keyInput = card.querySelector('#byok-key') as HTMLInputElement;
    const promptInput = card.querySelector('#byok-prompt') as HTMLTextAreaElement;
    const imageInput = card.querySelector('#byok-image') as HTMLInputElement;
    const goBtn = card.querySelector('#byok-go') as HTMLButtonElement;
    const progress = card.querySelector('#byok-progress') as HTMLElement;
    keyInput.value = localStorage.getItem('spaitial-api-key') ?? '';
    this.dialogProgressEl = progress;

    const close = () => {
      this.dialogReqId = null;
      this.dialogProgressEl = null;
      overlay.classList.remove('open');
    };
    (card.querySelector('#byok-close') as HTMLButtonElement).onclick = close;
    overlay.onclick = (e) => { if (e.target === overlay) close(); };

    // if a generation is already running, reflect it immediately
    const running = [...this.genState.values()].find((g) => !g.ready && !g.error);
    if (running) { this.dialogReqId = running.reqId; this.renderDialogProgress(); }

    goBtn.onclick = async () => {
      const key = keyInput.value.trim();
      if (!key.startsWith('spt_')) { progress.classList.add('show'); progress.textContent = 'Enter a valid API key (spt_live_… / spt_test_…)'; return; }
      localStorage.setItem('spaitial-api-key', key);

      const body: { prompt?: string; imageBase64?: string } = {};
      if (imageInput.files?.[0]) {
        progress.classList.add('show');
        progress.innerHTML = '<span class="spinner"></span>Reading image…';
        body.imageBase64 = await fileToDataUri(imageInput.files[0]);
      } else if (promptInput.value.trim()) {
        body.prompt = promptInput.value.trim();
      } else {
        progress.classList.add('show');
        progress.textContent = 'Describe the world or pick an image first';
        return;
      }

      goBtn.disabled = true;
      progress.classList.add('show');
      progress.innerHTML = '<span class="spinner"></span>Submitting to api.spaitial.ai…';
      try {
        const res = await fetch('/ext/create-world', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-spaitial-key': key },
          body: JSON.stringify(body),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data?.error?.message ?? data?.error ?? `HTTP ${res.status}`);
        const reqId = data.request_id as string;
        // hand off to the shared, dialog-independent poller
        this.startGeneration(reqId, '');
        this.dialogReqId = reqId;
        goBtn.disabled = false;
        this.renderDialogProgress();
      } catch (e) {
        goBtn.disabled = false;
        progress.classList.add('show');
        progress.textContent = `❌ ${(e as Error).message}`;
      }
    };

    // import / reuse an existing world by request or world id
    const importInput = card.querySelector('#byok-import') as HTMLInputElement;
    const importBtn = card.querySelector('#byok-import-go') as HTMLButtonElement;
    const doImport = async () => {
      const key = keyInput.value.trim();
      if (!key.startsWith('spt_')) { progress.classList.add('show'); progress.textContent = 'Enter your API key first'; return; }
      localStorage.setItem('spaitial-api-key', key);
      const id = importInput.value.trim();
      if (!/req_[0-9a-f]{32}/.test(id)) { progress.classList.add('show'); progress.textContent = 'Paste a request ID (req_…)'; return; }
      importBtn.disabled = true;
      progress.classList.add('show');
      progress.innerHTML = '<span class="spinner"></span>Looking up world via the API…';
      try {
        const res = await fetch('/ext/import-world', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', 'x-spaitial-key': key },
          body: JSON.stringify({ id }),
        });
        const data = await res.json();
        if (!res.ok) throw new Error(data?.error?.message ?? data?.error ?? `HTTP ${res.status}`);
        const reqId = data.request_id as string;
        this.startGeneration(reqId, '', Date.now(), 'downloading');
        this.dialogReqId = reqId;
        importBtn.disabled = false;
        this.renderDialogProgress();
      } catch (e) {
        importBtn.disabled = false;
        progress.classList.add('show');
        progress.textContent = `❌ ${(e as Error).message}`;
      }
    };
    importBtn.onclick = doImport;
    importInput.onkeydown = (e) => { if (e.key === 'Enter') doImport(); };
  }

  // ---------------- generation state (persists across dialog close + reload) ----------------

  private loadPending(): PendingGen[] {
    try { return JSON.parse(localStorage.getItem(PENDING_KEY) ?? '[]') as PendingGen[]; }
    catch { return []; }
  }
  private savePending(): void {
    const list = [...this.genState.values()]
      .filter((g) => !g.ready && !g.error)
      .map((g) => ({ reqId: g.reqId, title: g.title, startedAt: g.startedAt }));
    localStorage.setItem(PENDING_KEY, JSON.stringify(list));
  }

  // begin (or adopt) tracking a generation/import job
  startGeneration(reqId: string, title: string, startedAt = Date.now(), initialPhase = 'generating'): void {
    if (!this.genState.has(reqId)) {
      this.genState.set(reqId, { reqId, title, startedAt, phase: initialPhase });
    }
    this.savePending();
    this.renderGenChip();
    this.ensurePoller();
  }

  // on reload, re-adopt any jobs that were still running and (re)attach the
  // server to them using the stored key, in case the dev server restarted
  private resumePending(): void {
    const pending = this.loadPending();
    if (pending.length === 0) return;
    const key = localStorage.getItem('spaitial-api-key') ?? '';
    for (const p of pending) {
      this.genState.set(p.reqId, { ...p, phase: 'generating' });
      if (key) {
        fetch(`/ext/created/${p.reqId}/resume`, { method: 'POST', headers: { 'x-spaitial-key': key } }).catch(() => {});
      }
    }
    this.renderGenChip();
    this.ensurePoller();
    // delay so this lands after main.ts's generic boot toast rather than under it
    setTimeout(() => this.toast(`Resuming ${pending.length} world generation${pending.length > 1 ? 's' : ''} in progress…`), 1200);
  }

  private ensurePoller(): void {
    if (this.genPoll) return;
    const tick = () => void this.pollGenerations();
    this.genPoll = setInterval(tick, 5000);
    tick();
  }

  private async pollGenerations(): Promise<void> {
    const active = [...this.genState.values()].filter((g) => !g.ready && !g.error);
    if (active.length === 0) {
      if (this.genPoll) { clearInterval(this.genPoll); this.genPoll = null; }
      return;
    }
    for (const g of active) {
      try {
        const res = await fetch(`/ext/created/${g.reqId}/status`);
        if (res.status === 404) {
          // server forgot the job (restart). It can't recover without the key.
          const key = localStorage.getItem('spaitial-api-key') ?? '';
          if (key) { await fetch(`/ext/created/${g.reqId}/resume`, { method: 'POST', headers: { 'x-spaitial-key': key } }).catch(() => {}); continue; }
          g.error = 'generation lost (dev server restarted)';
        } else {
          const st = await res.json();
          if (st.title && !g.title) g.title = st.title;
          if (st.phase === 'ready') {
            g.ready = true;
            const title = g.title || `World ${g.reqId.slice(4, 10)}`;
            this.rememberCreatedWorld(g.reqId, title);
            this.addCustomWorld(`created:${g.reqId}`, `✨ ${title}`, false);
            if (this.dialogReqId === g.reqId) {
              this.cb.onWorldReady(`created:${g.reqId}`, title);
              this.dialogReqId = null;
              document.getElementById('dialog-overlay')?.classList.remove('open');
            } else {
              this.toast(`✨ "${title}" is ready — pick it in the World list`);
            }
          } else if (st.phase === 'error') {
            g.error = st.error ?? 'generation failed';
            this.toast(`❌ World generation failed: ${g.error}`);
          } else {
            g.phase = st.phase;
            g.detail = st.detail;
          }
        }
      } catch { /* transient poll error — try again next tick */ }
    }
    this.savePending();
    this.renderGenChip();
    this.renderDialogProgress();
  }

  private genLine(g: GenEntry): string {
    const mins = ((Date.now() - g.startedAt) / 60000).toFixed(1);
    const label = PHASE_LABEL[g.phase] ?? g.phase;
    const name = g.title ? `"${g.title}"` : 'world';
    return `${label}${g.detail ? ` — ${g.detail}` : ''} · ${name} · ${mins} min`;
  }

  private renderGenChip(): void {
    const active = [...this.genState.values()].filter((g) => !g.ready && !g.error);
    if (active.length === 0) { this.genChip.style.display = 'none'; return; }
    this.genChip.style.display = 'block';
    const head = active.length > 1 ? `${active.length} worlds generating` : this.genLine(active[0]);
    this.genChip.innerHTML = `<span class="spinner"></span>${head}`;
  }

  private renderDialogProgress(): void {
    if (!this.dialogProgressEl || !this.dialogReqId) return;
    const g = this.genState.get(this.dialogReqId);
    if (!g) return;
    this.dialogProgressEl.classList.add('show');
    if (g.ready) this.dialogProgressEl.innerHTML = `✅ <b>${g.title}</b> is ready — loading…`;
    else if (g.error) this.dialogProgressEl.innerHTML = `❌ ${g.error}`;
    else this.dialogProgressEl.innerHTML = `<span class="spinner"></span>${this.genLine(g)}<br><span style="color:var(--muted);font-size:11px">You can close this — progress keeps showing in the panel.</span>`;
  }

  toast(message: string): void {
    const t = document.getElementById('toast')!;
    t.textContent = message;
    t.classList.add('show');
    clearTimeout((t as any)._timer);
    (t as any)._timer = setTimeout(() => t.classList.remove('show'), 2600);
  }
}

function fileToDataUri(file: File): Promise<string> {
  return new Promise((res, rej) => {
    const r = new FileReader();
    r.onload = () => res(r.result as string);
    r.onerror = () => rej(new Error('could not read image'));
    r.readAsDataURL(file);
  });
}

function h(html: string): HTMLElement {
  const tpl = document.createElement('template');
  tpl.innerHTML = html.trim();
  return tpl.content.firstElementChild as HTMLElement;
}
function div(cls: string): HTMLElement {
  const d = document.createElement('div');
  d.className = cls;
  return d;
}
function btn(html: string, onClick: () => void): HTMLButtonElement {
  const b = document.createElement('button');
  b.innerHTML = html;
  b.onclick = onClick;
  return b;
}
function group(label: string): HTMLElement {
  const g = div('group');
  g.appendChild(h(`<div class="group-label">${label}</div>`));
  return g;
}
function formatNum(n: number): string {
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'k';
  return String(n);
}
