// SpAItial Bot — a humanoid bot learns to navigate 3D worlds generated by the
// Spaitial API, trained with a TypeScript port of PufferLib's PPO, live in
// your browser.

import * as pc from 'playcanvas';
import RAPIER from '@dimforge/rapier3d-compat';
import { Level, ViewMode } from './app/level';
import { Showcase } from './app/showcase';
import { OrbitCamera } from './app/camera';
import { Ui } from './app/ui';
import { toTransfer, groundHeight, isWalkable } from './sim/navgrid';
import { encodeCheckpoint, decodeCheckpoint } from './sim/checkpoint';
import { asset } from './util/paths';
import { TrainStats } from './sim/vectrain';
import { TaskConfig } from './sim/env';
import type { WorkerInMsg, WorkerOutMsg } from './trainer.worker';

const AUTOSAVE_KEY = 'spaitial-bot-autosave-v1';
const BALL_COLORS = [
  new pc.Color(0.937, 0.325, 0.314), new pc.Color(0.259, 0.647, 0.961),
  new pc.Color(0.4, 0.733, 0.416), new pc.Color(1.0, 0.933, 0.345),
  new pc.Color(0.671, 0.278, 0.737),
];

async function boot() {
  const setLoading = (step: string, frac: number) => {
    (document.getElementById('loading-fill') as HTMLElement).style.width = `${Math.round(frac * 100)}%`;
    (document.getElementById('loading-step') as HTMLElement).textContent = step;
  };
  setLoading('Initializing physics…', 0.02);
  await RAPIER.init();
  const world = new RAPIER.World({ x: 0, y: -9.81, z: 0 });

  const canvas = document.getElementById('app-canvas') as HTMLCanvasElement;
  const app = new pc.Application(canvas, {
    mouse: new pc.Mouse(canvas),
    touch: new pc.TouchDevice(canvas),
    keyboard: new pc.Keyboard(window),
    graphicsDeviceOptions: { antialias: true },
  });
  app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);
  app.setCanvasResolution(pc.RESOLUTION_AUTO);
  window.addEventListener('resize', () => app.resizeCanvas());
  app.start();

  // lights (the splat is unlit; these light the bot + markers)
  const sun = new pc.Entity('sun');
  sun.addComponent('light', { type: 'directional', intensity: 1.4, castShadows: false });
  sun.setEulerAngles(50, 30, 0);
  app.root.addChild(sun);
  app.scene.ambientLight = new pc.Color(0.45, 0.47, 0.55);

  // level
  const level = new Level(app, world);
  await level.load('gallery', setLoading);

  // camera + showcase bot
  const camera = new OrbitCamera(app, world, () => level.levelCollider);
  const showcase = new Showcase(app, level.grid);
  camera.target.set(showcase.env.x, 1.2, showcase.env.z);

  // ---------------- training worker ----------------
  const worker = new Worker(new URL('./trainer.worker.ts', import.meta.url), { type: 'module' });
  let latestWeights: Float32Array | null = null;
  let latestTrainedSteps = 0;
  let lastStats: TrainStats | null = null;
  let lastAutosave = 0;
  // true while the bot is showing an auto-loaded pretrained policy — every
  // scene load installs the task's pretrained so the bot is competent on
  // arrival. Flips false once the user trains, loads, or resets, after which
  // their weights carry across world/task swaps instead.
  let autoPolicy = true;

  const task: TaskConfig = { mode: 'nav', numBalls: 4, numDistractors: 3 };
  const workerSend = (msg: WorkerInMsg) => worker.postMessage(msg);
  const initWorker = () => workerSend({ type: 'init', grid: toTransfer(level.grid), seed: (Math.random() * 1e9) | 0, task: { ...task } });

  worker.onmessage = (ev: MessageEvent<WorkerOutMsg>) => {
    const msg = ev.data;
    if (msg.type === 'stats' && msg.stats) {
      lastStats = msg.stats;
      ui.updateStats(msg.stats, latestTrainedSteps);
    } else if (msg.type === 'weights' && msg.weights) {
      latestWeights = msg.weights;
      latestTrainedSteps = msg.trainedSteps ?? latestTrainedSteps;
      showcase.setWeights(msg.weights);
      const now = performance.now();
      if (ui.training && now - lastAutosave > 15000) {
        lastAutosave = now;
        autosave();
      }
    }
  };

  function autosave() {
    if (!latestWeights) return;
    try {
      const buf = encodeCheckpoint(showcase.policy, {
        trainedSteps: latestTrainedSteps,
        world: level.manifest.id,
        created: new Date().toISOString(),
        notes: 'browser autosave',
      });
      localStorage.setItem(AUTOSAVE_KEY, bufToB64(buf));
    } catch (e) {
      console.warn('autosave failed', e);
    }
  }

  function applyCheckpoint(buf: ArrayBuffer, label: string) {
    try {
      const { meta, weights } = decodeCheckpoint(buf);
      showcase.setWeights(weights);
      latestWeights = weights;
      latestTrainedSteps = meta.trainedSteps;
      autoPolicy = false; // explicit user load owns the policy now
      workerSend({ type: 'loadWeights', weights, trainedSteps: meta.trainedSteps });
      ui.toast(`${label}: ${(meta.trainedSteps / 1e6).toFixed(1)}M steps (${meta.world})`);
    } catch (e) {
      ui.toast(`Failed to load checkpoint: ${(e as Error).message}`);
    }
  }

  // ---------------- balls ----------------
  const balls: { body: RAPIER.RigidBody; entity: pc.Entity }[] = [];
  function spawnBall(colorIndex: number) {
    const r = 0.16;
    const t = camera.target;
    const x = t.x + (Math.random() - 0.5) * 0.8;
    const z = t.z + (Math.random() - 0.5) * 0.8;
    const y = (groundHeight(level.grid, x, z) || t.y) + 2.2;
    const body = world.createRigidBody(
      RAPIER.RigidBodyDesc.dynamic().setTranslation(x, y, z).setLinearDamping(0.3).setAngularDamping(0.4),
    );
    world.createCollider(RAPIER.ColliderDesc.ball(r).setRestitution(0.55).setFriction(0.8), body);
    const material = new pc.StandardMaterial();
    material.diffuse = BALL_COLORS[colorIndex % BALL_COLORS.length];
    material.gloss = 0.7;
    material.update();
    const entity = new pc.Entity('ball');
    entity.addComponent('render', { type: 'sphere', material });
    entity.setLocalScale(r * 2, r * 2, r * 2);
    app.root.addChild(entity);
    balls.push({ body, entity });
    if (balls.length > 40) {
      const old = balls.shift()!;
      world.removeRigidBody(old.body);
      old.entity.destroy();
    }
  }

  // Install the right policy after the worker is (re)initialised for a scene:
  // the task's pretrained checkpoint while autoPolicy holds, otherwise the
  // user's current weights carried across the swap.
  async function installScenePolicy(): Promise<'pretrained' | 'carried' | 'random'> {
    if (autoPolicy) {
      const file = task.mode === 'fetch' ? 'pretrained-fetch.pfbt' : 'pretrained.pfbt';
      try {
        const res = await fetch(asset(`checkpoints/${file}`));
        if (res.ok) {
          const { meta, weights } = decodeCheckpoint(await res.arrayBuffer());
          showcase.setWeights(weights);
          latestWeights = weights;
          latestTrainedSteps = meta.trainedSteps;
          workerSend({ type: 'loadWeights', weights: weights.slice(), trainedSteps: meta.trainedSteps });
          return 'pretrained';
        }
      } catch { /* no bundled checkpoint — fall through to random */ }
      return 'random'; // worker's fresh init already posted a random policy
    }
    if (latestWeights) {
      workerSend({ type: 'loadWeights', weights: latestWeights.slice(), trainedSteps: latestTrainedSteps });
      return 'carried';
    }
    return 'random';
  }

  // ---------------- world switching ----------------
  let switching = false;
  async function switchWorld(id: string) {
    if (switching || id === level.manifest.id) return;
    switching = true;
    const wasTraining = ui.training;
    workerSend({ type: 'pause' });
    ui.setTraining(false);
    const overlay = document.getElementById('loading')!;
    overlay.classList.remove('hidden');
    try {
      await level.load(id, setLoading);
      showcase.setGrid(level.grid);
      camera.target.set(showcase.env.x, 1.2, showcase.env.z);
      camera.distance = 4.2;
      // re-init trainer on the new grid, then install the scene's policy
      initWorker();
      const how = await installScenePolicy();
      ui.setViewMode(level.mode);
      if (id.startsWith('custom:')) ui.addCustomWorld(id, level.manifest.name);
      else ui.setWorld(id);
      const policyNote = how === 'pretrained' ? 'pretrained policy loaded'
        : how === 'carried' ? `your policy carried over${wasTraining ? ', training paused' : ''}`
        : 'untrained — press Start learning';
      ui.toast(`Switched to ${level.manifest.name} — ${policyNote}`);
    } catch (e) {
      ui.toast(`Failed to load world: ${(e as Error).message}`);
    } finally {
      overlay.classList.add('hidden');
      switching = false;
    }
  }

  // ---------------- UI ----------------
  const ui = new Ui({
    onTrainToggle: () => {
      if (ui.training) { workerSend({ type: 'pause' }); ui.setTraining(false); autosave(); }
      else { autoPolicy = false; workerSend({ type: 'start' }); ui.setTraining(true); } // user now owns the policy (fine-tuning from here)
    },
    onResetPolicy: () => {
      autoPolicy = false;
      if (ui.training) { workerSend({ type: 'pause' }); ui.setTraining(false); }
      initWorker(); // fresh random policy; the worker posts it straight back to the showcase
      ui.toast('Policy reset to random — press ▶ Start learning to train from scratch');
    },
    onSaveCheckpoint: () => {
      if (!latestWeights) { ui.toast('Nothing to save yet — start learning first'); return; }
      const buf = encodeCheckpoint(showcase.policy, {
        trainedSteps: latestTrainedSteps,
        world: level.manifest.id,
        created: new Date().toISOString(),
      });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(new Blob([buf], { type: 'application/octet-stream' }));
      a.download = `spaitial-bot-${level.manifest.id}-${(latestTrainedSteps / 1e6).toFixed(1)}M.pfbt`;
      a.click();
      URL.revokeObjectURL(a.href);
    },
    onLoadCheckpointFile: async (file) => applyCheckpoint(await file.arrayBuffer(), file.name),
    onLoadPretrained: async () => {
      const file = task.mode === 'fetch' ? 'pretrained-fetch.pfbt' : 'pretrained.pfbt';
      try {
        const res = await fetch(asset(`checkpoints/${file}`));
        if (!res.ok) throw new Error('no bundled checkpoint');
        applyCheckpoint(await res.arrayBuffer(), 'Pretrained');
      } catch {
        ui.toast(`No ${file} bundled yet — run: npm run pretrain${task.mode === 'fetch' ? ' -- --task fetch' : ''}`);
      }
    },
    onLoadAutosave: () => {
      const b64 = localStorage.getItem(AUTOSAVE_KEY);
      if (!b64) { ui.toast('No autosave found'); return; }
      applyCheckpoint(b64ToBuf(b64), 'Autosave');
    },
    onWorldChange: (id) => void switchWorld(id),
    onWorldReady: (levelId) => void switchWorld(levelId),
    onClimbChange: (height) => {
      if (level.manifest.collision.length === 0) {
        ui.toast('Climbing needs a collision mesh — create a world via the API for full physics');
        return;
      }
      const wasTraining = ui.training;
      if (wasTraining) { workerSend({ type: 'pause' }); ui.setTraining(false); }
      level.rebake(height);
      showcase.setGrid(level.grid);
      initWorker();
      void installScenePolicy();
      ui.toast(height > 0 ? `Max climb height ${height} m — navgrid rebaked` : 'Climbing off — stairs only');
    },
    onNewGoal: () => { showcase.newGoal(); ui.toast('New random goal set'); },
    onTaskChange: (mode, numBalls) => {
      task.mode = mode;
      task.numBalls = numBalls;
      const wasTraining = ui.training;
      if (wasTraining) { workerSend({ type: 'pause' }); ui.setTraining(false); }
      showcase.setTask(task);
      initWorker();
      void installScenePolicy();
      ui.toast(mode === 'fetch'
        ? `Task: fetch ${numBalls} blue ball${numBalls > 1 ? 's' : ''}${wasTraining ? ' — training paused' : ''}`
        : 'Task: navigate to the goal');
    },
    onViewMode: (mode: ViewMode) => { level.setMode(mode); ui.setViewMode(mode); },
    onToggleNav: () => ui.setToggle('nav', level.toggleNav()),
    onToggleCameraCollision: () => { camera.collision = !camera.collision; ui.setToggle('cam', camera.collision); },
    onToggleFollow: () => {
      camera.follow = !camera.follow;
      if (camera.follow) camera.resetFollow(showcase.env.yaw);
      ui.setToggle('follow', camera.follow);
    },
    onToggleGreedy: () => { showcase.greedy = !showcase.greedy; ui.setToggle('greedy', showcase.greedy); },
    onRespawn: () => showcase.respawn(),
    onSpawnBall: spawnBall,
  });

  ui.setToggle('cam', camera.collision);

  showcase.onEpisodeEnd = (success) => {
    if (success && !ui.training) {
      ui.toast(task.mode === 'fetch' ? '🏆 All balls delivered!' : '🎉 Goal reached');
    }
  };
  showcase.onTaskEvent = (event, remaining) => {
    if (ui.training) return;
    if (event === 'pickup') ui.toast(`🔵 Picked up a ball — carry it to the goal`);
    else if (remaining > 0) ui.toast(`✅ Delivered! ${remaining} ball${remaining > 1 ? 's' : ''} to go`);
  };

  initWorker();
  // start with the trained policy so the bot is competent on arrival
  installScenePolicy().then((how) => {
    if (how === 'pretrained') ui.toast('Pretrained policy loaded — ▶ Start learning to fine-tune, or ↺ Reset to train from scratch');
    else ui.toast('Press ▶ Start learning to train the bot');
  });

  // detect whether the world-generation backend is present (it isn't on a
  // static host like GitHub Pages) and gate BYOK/import accordingly
  fetch(asset('ext/health'))
    .then((r) => r.ok)
    .catch(() => false)
    .then((ok) => ui.setBackendAvailable(ok));

  // ---------------- input ----------------
  const keys: Record<string, () => void> = {
    b: () => { level.setMode('both'); ui.setViewMode('both'); },
    m: () => { level.setMode('mesh-overlay'); ui.setViewMode('mesh-overlay'); },
    p: () => { level.setMode('splat-only'); ui.setViewMode('splat-only'); },
    o: () => { level.setMode('mesh-only'); ui.setViewMode('mesh-only'); },
    n: () => ui.setToggle('nav', level.toggleNav()),
    c: () => { camera.collision = !camera.collision; ui.setToggle('cam', camera.collision); },
    f: () => {
      camera.follow = !camera.follow;
      if (camera.follow) camera.resetFollow(showcase.env.yaw);
      ui.setToggle('follow', camera.follow);
    },
    g: () => { showcase.greedy = !showcase.greedy; ui.setToggle('greedy', showcase.greedy); },
    r: () => showcase.respawn(),
    '1': () => spawnBall(0), '2': () => spawnBall(1), '3': () => spawnBall(2),
    '4': () => spawnBall(3), '5': () => spawnBall(4),
  };
  // WASD/QE free-fly (auto-disengages follow mode), shift = faster
  const moveKeys = new Set<string>();
  const MOVE_KEYS = ['w', 'a', 's', 'd', 'q', 'e'];
  // Don't let viewer shortcuts fire while the user is typing in a form field
  // or the BYOK dialog is open.
  const typingInUI = (e: KeyboardEvent): boolean => {
    const t = e.target as HTMLElement | null;
    if (t && (t.tagName === 'INPUT' || t.tagName === 'SELECT' || t.tagName === 'TEXTAREA' || t.isContentEditable)) return true;
    return document.getElementById('dialog-overlay')?.classList.contains('open') ?? false;
  };
  window.addEventListener('keydown', (e) => {
    if (typingInUI(e)) return;
    if (e.key === ' ') { e.preventDefault(); ui.training ? (workerSend({ type: 'pause' }), ui.setTraining(false)) : (workerSend({ type: 'start' }), ui.setTraining(true)); return; }
    const k = e.key.toLowerCase();
    if (MOVE_KEYS.includes(k)) { moveKeys.add(k); return; }
    keys[k]?.();
  });
  window.addEventListener('keyup', (e) => moveKeys.delete(e.key.toLowerCase()));
  window.addEventListener('blur', () => moveKeys.clear());

  // click (not drag) on floor sets the bot's goal
  let downX = 0, downY = 0, downT = 0;
  canvas.addEventListener('pointerdown', (e) => { downX = e.clientX; downY = e.clientY; downT = performance.now(); });
  canvas.addEventListener('pointerup', (e) => {
    if (Math.hypot(e.clientX - downX, e.clientY - downY) > 6 || performance.now() - downT > 400) return;
    const { origin, dir } = camera.screenRay(e.clientX, e.clientY);
    const ray = new RAPIER.Ray({ x: origin.x, y: origin.y, z: origin.z }, { x: dir.x, y: dir.y, z: dir.z });
    const hit = world.castRay(ray, 200, true, undefined, undefined, undefined, undefined,
      (c) => c === level.levelCollider);
    if (!hit) return;
    const px = origin.x + dir.x * hit.timeOfImpact;
    const pz = origin.z + dir.z * hit.timeOfImpact;
    if (showcase.clickGoal(px, pz)) ui.toast('Goal set — bot is on its way');
    else ui.toast('That spot is not walkable');
  });

  // ---------------- frame loop ----------------
  app.on('update', (dt: number) => {
    world.timestep = Math.min(dt, 1 / 30);
    world.step();
    for (const b of balls) {
      const t = b.body.translation();
      b.entity.setPosition(t.x, t.y, t.z);
      const q = b.body.rotation();
      b.entity.setRotation(q.x, q.y, q.z, q.w);
    }
    showcase.update(dt);
    const mf = (moveKeys.has('w') ? 1 : 0) - (moveKeys.has('s') ? 1 : 0);
    const mr = (moveKeys.has('d') ? 1 : 0) - (moveKeys.has('a') ? 1 : 0);
    const mu = (moveKeys.has('e') ? 1 : 0) - (moveKeys.has('q') ? 1 : 0);
    if (mf || mr || mu) {
      if (camera.follow) { camera.follow = false; ui.setToggle('follow', false); }
      camera.moveFree(mf, mr, mu, dt);
    }
    if (camera.follow) {
      const p = showcase.bot.position;
      camera.target.lerp(camera.target, new pc.Vec3(p.x, p.y + 0.8, p.z), Math.min(1, dt * 5));
      camera.chaseYaw(showcase.env.yaw, dt);
    }
    camera.update();
  });

  document.getElementById('loading')!.classList.add('hidden');
  // (the policy-loaded toast is shown by installScenePolicy above)
}

function bufToB64(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf);
  let s = '';
  for (let i = 0; i < bytes.length; i += 0x8000) {
    s += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return btoa(s);
}
function b64ToBuf(b64: string): ArrayBuffer {
  const s = atob(b64);
  const bytes = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) bytes[i] = s.charCodeAt(i);
  return bytes.buffer;
}

boot().catch((e) => {
  console.error(e);
  (document.getElementById('loading-step') as HTMLElement).textContent = `Boot failed: ${e.message}`;
});
